// Cursusaanbod per richting, overgenomen uit de interne marktverkenning
// "Korte omscholingscursussen" (stand juli 2026). Prijzen zijn indicatief en
// ex btw; rijen wisselen per startdatum. Bron per rij: de aanbiederswebsite.

import type { Bi } from "./data";

const bi = (nl: string, en: string): Bi => ({ nl, en });

export type CourseRichting = "sociaal" | "techniek";
export type BinnenMaand = "ja" | "deels" | "nee";
export type DuurCat = "dagen" | "weken" | "maanden";
export type VormCat = "klassikaal" | "online" | "blended" | "werkplek";
export type PrijsCat = "gratis" | "laag" | "midden" | "hoog" | "aanvraag";

export interface Course {
  richting: CourseRichting;
  veld: string; // key into veldLabels
  aanbieder: string;
  naam: string;
  duur: Bi;
  duurCat: DuurCat;
  binnenMaand: BinnenMaand;
  vorm: VormCat[];
  prijs: Bi;
  prijsCat: PrijsCat;
  erkenning: string;
  url?: string;
}

export const veldLabels: Record<string, Bi> = {
  // Sociaal
  onderwijs: bi("Onderwijs", "Education"),
  "sociale-ondersteuning": bi("Sociale ondersteuning", "Social support"),
  ouderenzorg: bi("Ouderenzorg", "Elderly care"),
  gehandicaptenzorg: bi("Gehandicaptenzorg en autisme", "Disability care and autism"),
  vluchtelingenhulp: bi("Vluchtelingenhulp", "Refugee support"),
  planning: bi("Planning en administratie", "Planning and administration"),
  // Techniek
  universeel: bi("Universele instapcertificaten", "Universal entry certificates"),
  installatie: bi("Installatietechniek", "Installation technology"),
  elektro: bi("Elektrotechniek", "Electrical engineering"),
  productie: bi("Productie en proces", "Production and process"),
  quality: bi("Kwaliteit en QA", "Quality and QA"),
  infra: bi("Infra (glasvezel, GWW)", "Infrastructure (fibre, civil)"),
  onderhoud: bi("Onderhoud en gebouwbeheer", "Maintenance and building systems"),
};

export const vormLabels: Record<VormCat, Bi> = {
  klassikaal: bi("Klassikaal", "Classroom"),
  online: bi("Online", "Online"),
  blended: bi("Blended", "Blended"),
  werkplek: bi("Op de werkplek", "On the job"),
};

export const duurCatLabels: Record<DuurCat, Bi> = {
  dagen: bi("Enkele dagen", "A few days"),
  weken: bi("1 tot 6 weken", "1 to 6 weeks"),
  maanden: bi("Maanden of langer", "Months or longer"),
};

export const binnenMaandLabels: Record<BinnenMaand, Bi> = {
  ja: bi("Ja", "Yes"),
  deels: bi("Deels", "Partly"),
  nee: bi("Nee", "No"),
};

export const prijsCatLabels: Record<PrijsCat, Bi> = {
  gratis: bi("Gratis of betaald werk", "Free or paid work"),
  laag: bi("Tot €500", "Up to €500"),
  midden: bi("€500 tot €1.500", "€500 to €1,500"),
  hoog: bi("Meer dan €1.500", "Over €1,500"),
  aanvraag: bi("Op aanvraag", "On request"),
};

export const courses: Course[] = [
  // ===== SOCIAAL: onderwijs =====
  {
    richting: "sociaal",
    veld: "onderwijs",
    aanbieder: "SBB / werkgever",
    naam: "Klassenassistent: vacature + praktijkverklaring op de werkplek",
    duur: bi("Flexibel, kan in weken", "Flexible, possible within weeks"),
    duurCat: "weken",
    binnenMaand: "ja",
    vorm: ["werkplek"],
    prijs: bi("Gratis (werkend leren)", "Free (learning on the job)"),
    prijsCat: "gratis",
    erkenning: "SBB-praktijkverklaring",
    url: "https://www.s-bb.nl/arbeidsmarktpartner/omscholen-en-bijscholen/diploma-certificaat-praktijkverklaring",
  },
  {
    richting: "sociaal",
    veld: "onderwijs",
    aanbieder: "STOC",
    naam: "Didactische ondersteuning basisonderwijs (mbo-certificaat)",
    duur: bi("Vergelijkbare trajecten 3 tot 6 maanden", "Comparable tracks run 3 to 6 months"),
    duurCat: "maanden",
    binnenMaand: "nee",
    vorm: ["blended"],
    prijs: bi("Op aanvraag", "On request"),
    prijsCat: "aanvraag",
    erkenning: "Mbo-certificaat",
    url: "https://www.stoc.nl/product/didactische-ondersteuning-basisonderwijs-mbo-certificaat/",
  },
  {
    richting: "sociaal",
    veld: "onderwijs",
    aanbieder: "LOI",
    naam: "Kort MBO-programma Onderwijsassistent",
    duur: bi("Zelf-tempo, nominaal 5 tot 7 maanden", "Self-paced, nominally 5 to 7 months"),
    duurCat: "maanden",
    binnenMaand: "nee",
    vorm: ["online", "blended"],
    prijs: bi("Maandtarief, op aanvraag", "Monthly fee, on request"),
    prijsCat: "aanvraag",
    erkenning: "Vrijstellingen richting mbo 4",
    url: "https://www.loi.nl/mbo/programma/onderwijsassistent",
  },
  {
    richting: "sociaal",
    veld: "onderwijs",
    aanbieder: "Capabel Onderwijs",
    naam: "MBO Onderwijsassistent verkort",
    duur: bi("15 maanden", "15 months"),
    duurCat: "maanden",
    binnenMaand: "nee",
    vorm: ["klassikaal", "werkplek"],
    prijs: bi("Op aanvraag", "On request"),
    prijsCat: "aanvraag",
    erkenning: "Mbo 4-diploma",
    url: "https://www.capabel.nl/opleidingen/onderwijs-kinderopvang/mbo-onderwijsassistent",
  },
  // ===== SOCIAAL: sociale ondersteuning =====
  {
    richting: "sociaal",
    veld: "sociale-ondersteuning",
    aanbieder: "Humanitas Academie",
    naam: "Basistraining vrijwilliger (maatjes, taalcoaching, thuisadministratie)",
    duur: bi("2 bijeenkomsten + e-learning", "2 sessions + e-learning"),
    duurCat: "dagen",
    binnenMaand: "ja",
    vorm: ["blended"],
    prijs: bi("Gratis (vrijwilligersrol)", "Free (volunteer role)"),
    prijsCat: "gratis",
    erkenning: "Directe maatje-rol, geen certificaat",
    url: "https://www.humanitas.nl/academie/vrijwilligers/",
  },
  {
    richting: "sociaal",
    veld: "sociale-ondersteuning",
    aanbieder: "KernKracht / MEE",
    naam: "Basistraining informeel onafhankelijk cliëntondersteuner",
    duur: bi("6 lessen van 3 uur", "6 lessons of 3 hours"),
    duurCat: "weken",
    binnenMaand: "ja",
    vorm: ["klassikaal"],
    prijs: bi("Gratis of laag", "Free or low"),
    prijsCat: "gratis",
    erkenning: "Instellingscertificaat",
    url: "https://www.kernkracht.nl/trainingen/training-werken-als-informeel-onafhankelijke-clientondersteuner-ioco/",
  },
  {
    richting: "sociaal",
    veld: "sociale-ondersteuning",
    aanbieder: "GGZ-instellingen",
    naam: "Basistraining ervaringsdeskundigheid",
    duur: bi("12 tot 13 bijeenkomsten, circa 3 maanden", "12 to 13 sessions, around 3 months"),
    duurCat: "maanden",
    binnenMaand: "nee",
    vorm: ["klassikaal"],
    prijs: bi("Gratis of laag", "Free or low"),
    prijsCat: "gratis",
    erkenning: "Instellingscertificaat",
    url: "https://www.ggzwnb.nl/basistraining-vrijwillige-ervaringsdeskundigen",
  },
  {
    richting: "sociaal",
    veld: "sociale-ondersteuning",
    aanbieder: "House of Skills (Amsterdam)",
    naam: "Oriëntatieprogramma Zorg & Welzijn",
    duur: bi("10 weken, start 4x per jaar", "10 weeks, starts 4x a year"),
    duurCat: "maanden",
    binnenMaand: "nee",
    vorm: ["klassikaal", "werkplek"],
    prijs: bi("Op aanvraag", "On request"),
    prijsCat: "aanvraag",
    erkenning: "Eventueel mbo-deelcertificaten",
    url: "https://www.houseofskillsregioamsterdam.nl/orientatieprogramma-zorg-en-welzijn/",
  },
  {
    richting: "sociaal",
    veld: "sociale-ondersteuning",
    aanbieder: "ROC van Twente",
    naam: "Mbo-certificaat Ervaringsdeskundigheid",
    duur: bi("40 weken, 2 uur per week", "40 weeks, 2 hours a week"),
    duurCat: "maanden",
    binnenMaand: "nee",
    vorm: ["klassikaal"],
    prijs: bi("Op aanvraag", "On request"),
    prijsCat: "aanvraag",
    erkenning: "Mbo-certificaat",
    url: "https://www.rocvantwente.nl/voor-volwassenen/werk-en-loopbaan/ervaringsdeskundige",
  },
  // ===== SOCIAAL: ouderenzorg =====
  {
    richting: "sociaal",
    veld: "ouderenzorg",
    aanbieder: "ROC Midden Nederland",
    naam: "Planmatig werken in zorg en welzijn (C0166)",
    duur: bi("2 lesdagen, doorlooptijd 1 tot 4 weken", "2 class days, spread over 1 to 4 weeks"),
    duurCat: "weken",
    binnenMaand: "ja",
    vorm: ["blended"],
    prijs: bi("€575", "€575"),
    prijsCat: "midden",
    erkenning: "Mbo-certificaat, leerwerkplek verplicht",
    url: "https://www.rocmn.nl/volwassenenonderwijs/opleidingen/planmatig-werken-in-zorg-en-welzijn",
  },
  {
    richting: "sociaal",
    veld: "ouderenzorg",
    aanbieder: "ROC Midden Nederland",
    naam: "Ondersteunen bij wonen en voeding",
    duur: bi("1 tot 4 weken", "1 to 4 weeks"),
    duurCat: "weken",
    binnenMaand: "ja",
    vorm: ["klassikaal"],
    prijs: bi("Op aanvraag", "On request"),
    prijsCat: "aanvraag",
    erkenning: "Mbo-certificaat, leerwerkplek verplicht",
    url: "https://www.rocmn.nl/volwassenenonderwijs/opleidingen/ondersteunen-bij-wonen-en-voeding",
  },
  {
    richting: "sociaal",
    veld: "ouderenzorg",
    aanbieder: "ROC Midden Nederland",
    naam: "Assisteren bij activiteiten in zorg en welzijn",
    duur: bi("3 lesdagen, 1 tot 3 maanden", "3 class days, 1 to 3 months"),
    duurCat: "maanden",
    binnenMaand: "deels",
    vorm: ["klassikaal"],
    prijs: bi("Op aanvraag", "On request"),
    prijsCat: "aanvraag",
    erkenning: "Mbo-certificaat, leerwerkplek verplicht",
    url: "https://www.rocmn.nl/volwassenenonderwijs/opleidingen/assisteren-bij-activiteiten-in-zorg-en-welzijn",
  },
  {
    richting: "sociaal",
    veld: "ouderenzorg",
    aanbieder: "Nationale Zorgklas",
    naam: "Ondersteunend Zorgverlener / Huiskamerbegeleider + mbo-certificaten",
    duur: bi("1 tot 2 weken, actuele duur per opleider", "1 to 2 weeks, current length varies by provider"),
    duurCat: "weken",
    binnenMaand: "deels",
    vorm: ["blended"],
    prijs: bi("Via werkgever", "Via the employer"),
    prijsCat: "aanvraag",
    erkenning: "Branche-instap en mbo-certificaten",
    url: "https://nationalezorgklas.nl/opleidingsaanbod",
  },
  {
    richting: "sociaal",
    veld: "ouderenzorg",
    aanbieder: "ROC van Amsterdam",
    naam: "Individuele basiszorg verlenen (C0039)",
    duur: bi("13 weken, 1 tot 2 lesdagen per week + praktijk", "13 weeks, 1 to 2 class days a week + practice"),
    duurCat: "maanden",
    binnenMaand: "nee",
    vorm: ["klassikaal", "werkplek"],
    prijs: bi("€1.350", "€1,350"),
    prijsCat: "midden",
    erkenning: "Mbo-certificaat (deel Helpende ZW)",
    url: "https://www.rocva.nl/volwassenen/sectoren/zorg-welzijn/individuele-basiszorg",
  },
  {
    richting: "sociaal",
    veld: "ouderenzorg",
    aanbieder: "Da Vinci College",
    naam: "Mbo-certificaat Individuele zorg verlenen (C0053)",
    duur: bi("Circa 12 weken + 2 tot 4 weken examen", "About 12 weeks + 2 to 4 weeks of exams"),
    duurCat: "maanden",
    binnenMaand: "nee",
    vorm: ["klassikaal", "werkplek"],
    prijs: bi("Op aanvraag", "On request"),
    prijsCat: "aanvraag",
    erkenning: "Mbo-certificaat, werkgever vereist",
    url: "https://www.davinci.nl/zakelijk/aanbod/cursussen-trainingen/mbo-certificaat-individuele-zorg-verlenen/",
  },
  {
    richting: "sociaal",
    veld: "ouderenzorg",
    aanbieder: "ROC van Twente / STOC / Firda",
    naam: "Helpende Plus (K1296)",
    duur: bi("20 weken, 10 bijeenkomsten", "20 weeks, 10 sessions"),
    duurCat: "maanden",
    binnenMaand: "nee",
    vorm: ["klassikaal"],
    prijs: bi("Op aanvraag", "On request"),
    prijsCat: "aanvraag",
    erkenning: "Mbo-certificaat",
    url: "https://www.rocvantwente.nl/voor-volwassenen/werk-en-loopbaan/helpende-plus",
  },
  // ===== SOCIAAL: gehandicaptenzorg / autisme =====
  {
    richting: "sociaal",
    veld: "gehandicaptenzorg",
    aanbieder: "RINO Groep",
    naam: "Basiscursus begeleiden van mensen met autisme",
    duur: bi("3 lesdagen + circa 5 uur praktijkopdrachten", "3 class days + about 5 hours of practice work"),
    duurCat: "dagen",
    binnenMaand: "ja",
    vorm: ["klassikaal"],
    prijs: bi("Op aanvraag", "On request"),
    prijsCat: "aanvraag",
    erkenning: "Certificaat, CRKBO, SKJ-punten",
    url: "https://www.rinogroep.nl/opleiding/7189/basiscursus-begeleiden-van-mensen-met-autisme.html",
  },
  {
    richting: "sociaal",
    veld: "gehandicaptenzorg",
    aanbieder: "SBB / zorgorganisatie",
    naam: "Leerwerkplek gehandicaptenzorg + praktijkverklaring",
    duur: bi("Flexibel, kan in weken", "Flexible, possible within weeks"),
    duurCat: "weken",
    binnenMaand: "ja",
    vorm: ["werkplek"],
    prijs: bi("Gratis (werkend leren)", "Free (learning on the job)"),
    prijsCat: "gratis",
    erkenning: "SBB-praktijkverklaring",
    url: "https://www.s-bb.nl/arbeidsmarktpartner/omscholen-en-bijscholen/diploma-certificaat-praktijkverklaring",
  },
  {
    richting: "sociaal",
    veld: "gehandicaptenzorg",
    aanbieder: "Nationale Zorgklas",
    naam: "Mbo-certificaten maatschappelijke zorg (C0098 / C0100)",
    duur: bi("Duur per opleider", "Length varies by provider"),
    duurCat: "weken",
    binnenMaand: "deels",
    vorm: ["blended"],
    prijs: bi("Via werkgever", "Via the employer"),
    prijsCat: "aanvraag",
    erkenning: "Mbo-certificaat (deel Begeleider MZ)",
    url: "https://nationalezorgklas.nl/opleidingsaanbod",
  },
  {
    richting: "sociaal",
    veld: "gehandicaptenzorg",
    aanbieder: "Firda",
    naam: "Ondersteunen en begeleiden in de maatschappelijke zorg (C0101)",
    duur: bi("Circa 15 weken, 1 dagdeel per week", "About 15 weeks, one session a week"),
    duurCat: "maanden",
    binnenMaand: "nee",
    vorm: ["klassikaal"],
    prijs: bi("Op aanvraag", "On request"),
    prijsCat: "aanvraag",
    erkenning: "Mbo-certificaat",
    url: "https://www.firda.nl/volwassenen/opleidingen/ondersteunen-en-begeleiden-de-maatschappelijke-zorg-c0101",
  },
  {
    richting: "sociaal",
    veld: "gehandicaptenzorg",
    aanbieder: "Windesheim",
    naam: "Post-mbo Autismebegeleider",
    duur: bi("8 vrijdagen verspreid over 1 jaar", "8 Fridays spread over a year"),
    duurCat: "maanden",
    binnenMaand: "nee",
    vorm: ["klassikaal"],
    prijs: bi("Op aanvraag", "On request"),
    prijsCat: "aanvraag",
    erkenning: "Post-mbo-certificaat",
    url: "https://www.windesheim.nl/opleidingen/deeltijd/cursus/autismebegeleider",
  },
  // ===== SOCIAAL: vluchtelingenhulp =====
  {
    richting: "sociaal",
    veld: "vluchtelingenhulp",
    aanbieder: "VluchtelingenWerk Academie",
    naam: "Basiscursus maatschappelijk begeleider / taalcoach",
    duur: bi("2 volledige dagen", "2 full days"),
    duurCat: "dagen",
    binnenMaand: "ja",
    vorm: ["klassikaal"],
    prijs: bi("Gratis (bij vrijwilligersrol)", "Free (with a volunteer role)"),
    prijsCat: "gratis",
    erkenning: "Intern certificaat",
    url: "https://www.vluchtelingenwerk.nl/nl/training-en-cursussen",
  },
  {
    richting: "sociaal",
    veld: "vluchtelingenhulp",
    aanbieder: "Pharos",
    naam: "Werken met mensen met een vluchtelingenachtergrond",
    duur: bi("1 tot 2 dagen", "1 to 2 days"),
    duurCat: "dagen",
    binnenMaand: "ja",
    vorm: ["klassikaal"],
    prijs: bi("Op aanvraag", "On request"),
    prijsCat: "aanvraag",
    erkenning: "Certificaat kennisinstituut",
    url: "https://www.pharos.nl/training/werken-met-mensen-met-een-vluchtelingenachtergrond/",
  },
  // ===== SOCIAAL: planning / administratie =====
  {
    richting: "sociaal",
    veld: "planning",
    aanbieder: "Hello! Planner",
    naam: "Vakopleiding personeelsplanning zorg",
    duur: bi("4 lesdagen (40 uur)", "4 class days (40 hours)"),
    duurCat: "dagen",
    binnenMaand: "ja",
    vorm: ["klassikaal"],
    prijs: bi("Op aanvraag", "On request"),
    prijsCat: "aanvraag",
    erkenning: "Branchegericht instituutscertificaat",
    url: "https://www.helloplanner.nl/opleidingen/vakopleiding-personeelsplanning-zorg/",
  },
  {
    richting: "sociaal",
    veld: "planning",
    aanbieder: "Hello! Planner / Q-academy",
    naam: "Basistraining roosteren in de zorg",
    duur: bi("2 lesdagen", "2 class days"),
    duurCat: "dagen",
    binnenMaand: "ja",
    vorm: ["klassikaal"],
    prijs: bi("Op aanvraag", "On request"),
    prijsCat: "aanvraag",
    erkenning: "Certificaat",
    url: "https://www.helloplanner.nl/opleidingen/roosteren/",
  },
  {
    richting: "sociaal",
    veld: "planning",
    aanbieder: "Nationale Zorgklas",
    naam: "Voorbereiden van ondersteunende begeleiding en zorg (C0079)",
    duur: bi("Duur per opleider", "Length varies by provider"),
    duurCat: "weken",
    binnenMaand: "deels",
    vorm: ["blended"],
    prijs: bi("Via werkgever", "Via the employer"),
    prijsCat: "aanvraag",
    erkenning: "Mbo-certificaat",
    url: "https://nationalezorgklas.nl/opleidingsaanbod",
  },
  {
    richting: "sociaal",
    veld: "planning",
    aanbieder: "HAN",
    naam: "Post-hbo Plannen in de Zorg",
    duur: bi("Kort, enkele dagen", "Short, a few days"),
    duurCat: "dagen",
    binnenMaand: "deels",
    vorm: ["klassikaal"],
    prijs: bi("Op aanvraag", "On request"),
    prijsCat: "aanvraag",
    erkenning: "Post-hbo-certificaat",
    url: "https://www.han.nl/opleidingen/post-hbo/plannen-in-de-zorg/",
  },
  {
    richting: "sociaal",
    veld: "planning",
    aanbieder: "MEEK2 / BCMB",
    naam: "Opleiding cliëntondersteuner (beroeps)",
    duur: bi("40 tot 140 uur over 6 tot 12 maanden", "40 to 140 hours over 6 to 12 months"),
    duurCat: "maanden",
    binnenMaand: "nee",
    vorm: ["blended"],
    prijs: bi("Op aanvraag", "On request"),
    prijsCat: "aanvraag",
    erkenning: "Registerplein-geaccrediteerd",
    url: "https://meek2.nl/volledig-aanbod/opleiding-tot-clientondersteuner/",
  },

  // ===== TECHNIEK: universele instapcertificaten =====
  {
    richting: "techniek",
    veld: "universeel",
    aanbieder: "CursusGeregeld e.a.",
    naam: "VCA Basis (B-VCA)",
    duur: bi("1 dag, inclusief examen", "1 day, exam included"),
    duurCat: "dagen",
    binnenMaand: "ja",
    vorm: ["klassikaal", "online"],
    prijs: bi("€119 tot €189", "€119 to €189"),
    prijsCat: "laag",
    erkenning: "SSVV-persoonscertificaat, 10 jaar geldig",
    url: "https://cursusgeregeld.nl/cursus/vca-basis-1-dag",
  },
  {
    richting: "techniek",
    veld: "universeel",
    aanbieder: "VCA Nederland e.a.",
    naam: "VCA VOL (voorlieden en zzp)",
    duur: bi("1 dag", "1 day"),
    duurCat: "dagen",
    binnenMaand: "ja",
    vorm: ["klassikaal", "online"],
    prijs: bi("€150 tot €250", "€150 to €250"),
    prijsCat: "laag",
    erkenning: "SSVV-persoonscertificaat, 10 jaar geldig",
    url: "https://www.vcanederland.nl/producten/itemcode/vca-vol-cursus-examen-1-dag",
  },
  {
    richting: "techniek",
    veld: "universeel",
    aanbieder: "101BHV / ProBHV e.a.",
    naam: "BHV basis",
    duur: bi("1 dag", "1 day"),
    duurCat: "dagen",
    binnenMaand: "ja",
    vorm: ["klassikaal"],
    prijs: bi("€169 tot €249", "€169 to €249"),
    prijsCat: "laag",
    erkenning: "NIBHV-certificaat, jaarlijkse herhaling",
    url: "https://www.101bhv.nl/bhv-cursus/bhv-cursus-1-dag/",
  },
  {
    richting: "techniek",
    veld: "universeel",
    aanbieder: "Heftruckcertificaat.nl / VTC e.a.",
    naam: "Heftruckcertificaat",
    duur: bi("Halve tot hele dag", "Half a day to a full day"),
    duurCat: "dagen",
    binnenMaand: "ja",
    vorm: ["klassikaal"],
    prijs: bi("€129 tot €334", "€129 to €334"),
    prijsCat: "laag",
    erkenning: "Branchecertificaat, breed geaccepteerd",
    url: "https://www.heftruckcertificaat.nl/",
  },
  {
    richting: "techniek",
    veld: "universeel",
    aanbieder: "ARBO Centrum / VCA Groep e.a.",
    naam: "NEN 3140 VOP",
    duur: bi("1 dag (online vanaf 2 uur)", "1 day (online from 2 hours)"),
    duurCat: "dagen",
    binnenMaand: "ja",
    vorm: ["klassikaal", "online"],
    prijs: bi("€89 tot €375", "€89 to €375"),
    prijsCat: "laag",
    erkenning: "Persoonscertificaat, 3 jaar geldig",
    url: "https://www.arbocentrum.nl/nen3140-cursus/nen-3140-vop/",
  },
  {
    richting: "techniek",
    veld: "universeel",
    aanbieder: "ARBO Centrum / Mennens",
    naam: "Veilig hijsen en aanslaan van lasten",
    duur: bi("1 dag", "1 day"),
    duurCat: "dagen",
    binnenMaand: "ja",
    vorm: ["klassikaal"],
    prijs: bi("€219 tot €519", "€219 to €519"),
    prijsCat: "laag",
    erkenning: "Certificaat 5 jaar, EKH-erkend",
    url: "https://www.mennens.nl/diensten/training/cursus-veilig-hijsen-en-aanslaan-van-lasten",
  },
  // ===== TECHNIEK: installatietechniek =====
  {
    richting: "techniek",
    veld: "installatie",
    aanbieder: "ROVC",
    naam: "Warmtepompen: typen, toepassing en basiswerking",
    duur: bi("Korte cursus, enkele lesdagen", "Short course, a few class days"),
    duurCat: "dagen",
    binnenMaand: "ja",
    vorm: ["klassikaal"],
    prijs: bi("€1.035", "€1,035"),
    prijsCat: "midden",
    erkenning: "ROVC-certificaat",
    url: "https://www.rovc.nl/cursus/warmtepompen-typen-toepassing-en-basiswerking",
  },
  {
    richting: "techniek",
    veld: "installatie",
    aanbieder: "ROVC",
    naam: "Warmtepompinstallaties: inspectie, onderhoud, storingen",
    duur: bi("Korte cursus", "Short course"),
    duurCat: "dagen",
    binnenMaand: "ja",
    vorm: ["klassikaal"],
    prijs: bi("Op aanvraag", "On request"),
    prijsCat: "aanvraag",
    erkenning: "ROVC-certificaat",
    url: "https://www.rovc.nl/cursus/warmtepompinstallaties-inspecties-onderhoud-en-storingen",
  },
  {
    richting: "techniek",
    veld: "installatie",
    aanbieder: "Strevon",
    naam: "Omscholing installatiemonteur (werken + leren)",
    duur: bi("In dienst vanaf dag 1, opleiding modulair", "Employed from day 1, modular training"),
    duurCat: "maanden",
    binnenMaand: "ja",
    vorm: ["werkplek"],
    prijs: bi("Betaald werk in plaats van cursusgeld", "Paid work instead of course fees"),
    prijsCat: "gratis",
    erkenning: "Mbo-certificaten onderweg",
    url: "https://strevon.nl/omscholen/installatiemonteur/",
  },
  {
    richting: "techniek",
    veld: "installatie",
    aanbieder: "IW Nederland",
    naam: "Leerwerktraject installatietechniek zij-instroom",
    duur: bi("Circa 18 maanden, in dienst vanaf maand 1", "About 18 months, employed from month 1"),
    duurCat: "maanden",
    binnenMaand: "deels",
    vorm: ["werkplek"],
    prijs: bi("Salaris conform cao", "Salary per collective agreement"),
    prijsCat: "gratis",
    erkenning: "Mbo-certificaten / BBL-diploma",
    url: "https://iw.nl/",
  },
  // ===== TECHNIEK: elektro =====
  {
    richting: "techniek",
    veld: "elektro",
    aanbieder: "ROVC",
    naam: "Elektrotechniek voor huis en utiliteit: basis",
    duur: bi("4 lesdagen", "4 class days"),
    duurCat: "dagen",
    binnenMaand: "ja",
    vorm: ["klassikaal"],
    prijs: bi("Op aanvraag", "On request"),
    prijsCat: "aanvraag",
    erkenning: "ROVC-certificaat",
    url: "https://www.rovc.nl/cursus/elektrotechniek-voor-huis-en-utiliteit-basis",
  },
  {
    richting: "techniek",
    veld: "elektro",
    aanbieder: "ROVC",
    naam: "Vakopleiding Monteur elektrotechnische installaties",
    duur: bi("7 praktijklesdagen, eigen tempo", "7 practical class days, own pace"),
    duurCat: "weken",
    binnenMaand: "deels",
    vorm: ["klassikaal"],
    prijs: bi("Op maat", "Tailored"),
    prijsCat: "aanvraag",
    erkenning: "Branche-erkend ROVC-diploma, mbo 2-niveau",
    url: "https://www.rovc.nl/opleiding/monteur-elektrotechnische-installaties",
  },
  {
    richting: "techniek",
    veld: "elektro",
    aanbieder: "ARBO Centrum / Dirksen e.a.",
    naam: "NEN 3140 VP (Vakbekwaam Persoon)",
    duur: bi("1 tot 2 dagen", "1 to 2 days"),
    duurCat: "dagen",
    binnenMaand: "ja",
    vorm: ["klassikaal"],
    prijs: bi("€300 tot €500", "€300 to €500"),
    prijsCat: "laag",
    erkenning: "Persoonscertificaat, 3 jaar geldig",
    url: "https://www.arbocentrum.nl/nen3140-cursus/",
  },
  {
    richting: "techniek",
    veld: "elektro",
    aanbieder: "Randstad",
    naam: "Opleiding zonnepanelenmonteur (werken en leren)",
    duur: bi("2 dagen + baan", "2 days + a job"),
    duurCat: "dagen",
    binnenMaand: "ja",
    vorm: ["klassikaal", "werkplek"],
    prijs: bi("Gratis via Randstad", "Free via Randstad"),
    prijsCat: "gratis",
    erkenning: "Inclusief veilig werken op hoogte",
    url: "https://www.randstad.nl/werknemers/opleidingen/techniek/zonnepanelen-monteur",
  },
  {
    richting: "techniek",
    veld: "elektro",
    aanbieder: "BDA Opleidingen",
    naam: "Monteur zonnestroominstallaties onder het dak (VP)",
    duur: bi("3 dagen", "3 days"),
    duurCat: "dagen",
    binnenMaand: "ja",
    vorm: ["klassikaal"],
    prijs: bi("€1.550", "€1,550"),
    prijsCat: "hoog",
    erkenning: "InstallQ-examenlijn, dé branche-erkenning",
    url: "https://bdaopleidingen.eu/cursus/installq-monteur-zonnestroominstallaties-onder-het-dak-vp/",
  },
  {
    richting: "techniek",
    veld: "elektro",
    aanbieder: "InstallQ-erkende opleiders",
    naam: "InstallQ-erkenningsroute zonnestroom (3 cursussen)",
    duur: bi("6 dagen totaal", "6 days in total"),
    duurCat: "dagen",
    binnenMaand: "ja",
    vorm: ["klassikaal"],
    prijs: bi("Varieert per opleider", "Varies by provider"),
    prijsCat: "aanvraag",
    erkenning: "Bewijs van Vakbekwaamheid (InstallQ)",
    url: "https://installq.nl/zonnestroominstallaties-pv",
  },
  {
    richting: "techniek",
    veld: "elektro",
    aanbieder: "OPECO",
    naam: "Zonnepanelenmonteur (1-daags)",
    duur: bi("1 dag", "1 day"),
    duurCat: "dagen",
    binnenMaand: "ja",
    vorm: ["klassikaal"],
    prijs: bi("Zie site", "See site"),
    prijsCat: "aanvraag",
    erkenning: "Deelnamecertificaat",
    url: "https://www.opeco.nl/i/zonnepanelencursus",
  },
  {
    richting: "techniek",
    veld: "elektro",
    aanbieder: "Firda (ROC)",
    naam: "Installatie PV-panelen (kort traject volwassenen)",
    duur: bi("Kort traject", "Short track"),
    duurCat: "dagen",
    binnenMaand: "ja",
    vorm: ["klassikaal"],
    prijs: bi("Zie site", "See site"),
    prijsCat: "aanvraag",
    erkenning: "ROC-certificaat",
    url: "https://www.firda.nl/volwassenen/opleidingen/installatie-pv-panelen",
  },
  {
    richting: "techniek",
    veld: "elektro",
    aanbieder: "BDA / Dirksen / ROVC",
    naam: "Laadpalen installeren",
    duur: bi("1 tot 4 dagen", "1 to 4 days"),
    duurCat: "dagen",
    binnenMaand: "ja",
    vorm: ["klassikaal"],
    prijs: bi("€650 tot €960", "€650 to €960"),
    prijsCat: "midden",
    erkenning: "Certificaat, o.a. gekoppeld aan NEN 3140 VP",
    url: "https://www.dirksen.nl/opleiding/276/installeren-laadpalen-volgens-nen-3140-vp",
  },
  // ===== TECHNIEK: productie / proces =====
  {
    richting: "techniek",
    veld: "productie",
    aanbieder: "Diverse aanbieders",
    naam: "Startpakket productiemedewerker: VCA + heftruck + HACCP",
    duur: bi("3 losse dagen", "3 separate days"),
    duurCat: "dagen",
    binnenMaand: "ja",
    vorm: ["klassikaal"],
    prijs: bi("€300 tot €700 totaal", "€300 to €700 in total"),
    prijsCat: "laag",
    erkenning: "Losse persoonscertificaten",
  },
  {
    richting: "techniek",
    veld: "productie",
    aanbieder: "VAPRO",
    naam: "VAPRO Basisoperator",
    duur: bi("8 maanden, 10 uur per week naast betaald werk", "8 months, 10 hours a week alongside paid work"),
    duurCat: "maanden",
    binnenMaand: "nee",
    vorm: ["werkplek", "online"],
    prijs: bi("Op aanvraag (meestal werkgever)", "On request (usually the employer)"),
    prijsCat: "aanvraag",
    erkenning: "Landelijk erkend VAPRO-diploma",
    url: "https://www.vapro.nl/operators/opleidingen/operator/vapro-basisoperator",
  },
  {
    richting: "techniek",
    veld: "productie",
    aanbieder: "Randstad / Timing / YoungCapital NEXT",
    naam: "Operator BBL-trajecten (baan + opleiding)",
    duur: bi("In dienst vanaf dag 1, bootcamp 1 tot 12 weken", "Employed from day 1, bootcamp of 1 to 12 weeks"),
    duurCat: "weken",
    binnenMaand: "deels",
    vorm: ["werkplek"],
    prijs: bi("Betaald werk", "Paid work"),
    prijsCat: "gratis",
    erkenning: "Mbo- en VAPRO-certificaten",
    url: "https://next.youngcapital.nl/traineeships/techniek",
  },
  // ===== TECHNIEK: quality / QA =====
  {
    richting: "techniek",
    veld: "quality",
    aanbieder: "SHO / HSN / KHN e.a.",
    naam: "HACCP-cursus klassikaal",
    duur: bi("1 dag", "1 day"),
    duurCat: "dagen",
    binnenMaand: "ja",
    vorm: ["klassikaal"],
    prijs: bi("€55 tot €360", "€55 to €360"),
    prijsCat: "laag",
    erkenning: "HACCP-certificaat, 3 jaar geldig",
    url: "https://www.sho-horeca.nl/cursussen/haccp/haccp-dag/",
  },
  {
    richting: "techniek",
    veld: "quality",
    aanbieder: "ToetsJeKennis e.a.",
    naam: "HACCP online",
    duur: bi("Circa 2 uur", "About 2 hours"),
    duurCat: "dagen",
    binnenMaand: "ja",
    vorm: ["online"],
    prijs: bi("€50 inclusief btw", "€50 incl. VAT"),
    prijsCat: "laag",
    erkenning: "Certificaat",
    url: "https://toetsjekennis.nl/haccp-cursus/",
  },
  {
    richting: "techniek",
    veld: "quality",
    aanbieder: "Normec Foodcare",
    naam: "Workshop basis voedselveiligheid",
    duur: bi("1 dag", "1 day"),
    duurCat: "dagen",
    binnenMaand: "ja",
    vorm: ["klassikaal"],
    prijs: bi("€455", "€455"),
    prijsCat: "laag",
    erkenning: "Deelnamecertificaat",
    url: "https://normecfoodcare.com/trainingen/opleiding-kwaliteitsmedewerker/",
  },
  {
    richting: "techniek",
    veld: "quality",
    aanbieder: "Normec Foodcare",
    naam: "3-daagse opleiding Kwaliteitsmedewerker",
    duur: bi("3 dagen (internaat)", "3 days (residential)"),
    duurCat: "dagen",
    binnenMaand: "ja",
    vorm: ["klassikaal"],
    prijs: bi("€2.477", "€2,477"),
    prijsCat: "hoog",
    erkenning: "Branchegericht certificaat, sterke naam in food-QA",
    url: "https://normecfoodcare.com/training/opleiding-kwaliteitsmedewerker/",
  },
  {
    richting: "techniek",
    veld: "quality",
    aanbieder: "Patagonia",
    naam: "Praktijkopleiding Kwaliteitsmedewerker ISO 9001",
    duur: bi("5 dagdelen", "5 half-days"),
    duurCat: "dagen",
    binnenMaand: "ja",
    vorm: ["klassikaal"],
    prijs: bi("€650", "€650"),
    prijsCat: "midden",
    erkenning: "Certificaat",
    url: "https://www.patagonia-opleidingen.com/trainingen-opleidingen/kwaliteitsmedewerker/",
  },
  {
    richting: "techniek",
    veld: "quality",
    aanbieder: "Kader Academy",
    naam: "Normkennis Kwaliteit ISO 9001",
    duur: bi("1 tot 2 dagen", "1 to 2 days"),
    duurCat: "dagen",
    binnenMaand: "ja",
    vorm: ["klassikaal"],
    prijs: bi("Zie site", "See site"),
    prijsCat: "aanvraag",
    erkenning: "Certificaat, gevestigde QHSE-opleider",
    url: "https://kader-academy.nl/milieu-en-kwaliteit/normkennis-kwaliteit-iso-9001",
  },
  // ===== TECHNIEK: infra =====
  {
    richting: "techniek",
    veld: "infra",
    aanbieder: "Dirksen",
    naam: "Monteur glasvezeltechniek ondergronds / bovengronds",
    duur: bi("8 dagen elk, over meerdere weken", "8 days each, over several weeks"),
    duurCat: "weken",
    binnenMaand: "deels",
    vorm: ["klassikaal"],
    prijs: bi("Zie site", "See site"),
    prijsCat: "aanvraag",
    erkenning: "CKB-erkend persoonscertificaat, 3 jaar geldig",
    url: "https://www.dirksen.nl/opleiding/189/monteur-glasvezeltechniek-ondergronds",
  },
  {
    richting: "techniek",
    veld: "infra",
    aanbieder: "Technisch Opleidingscentrum Zuid",
    naam: "Glasvezelmonteur korte opleiding",
    duur: bi("Kort traject", "Short track"),
    duurCat: "weken",
    binnenMaand: "deels",
    vorm: ["klassikaal"],
    prijs: bi("Zie site", "See site"),
    prijsCat: "aanvraag",
    erkenning: "Praktijkcertificaat",
    url: "https://technischopleidingscentrumzuid.nl/korte-opleiding/glasvezelmonteur/",
  },
  {
    richting: "techniek",
    veld: "infra",
    aanbieder: "Klict",
    naam: "FttX-cursussen zonder voorkennis / CKB Certified",
    duur: bi("Enkele dagen", "A few days"),
    duurCat: "dagen",
    binnenMaand: "ja",
    vorm: ["klassikaal"],
    prijs: bi("Zie site", "See site"),
    prijsCat: "aanvraag",
    erkenning: "CKB-lijn",
    url: "https://klict.nl/cursus-30229-zonder-basiskennis-glasvezel/",
  },
  {
    richting: "techniek",
    veld: "infra",
    aanbieder: "BME Opleidingen",
    naam: "Korte veiligheids- en rioolcursussen (asbest, riolering, sloop, gasmeten)",
    duur: bi("1 tot enkele dagen", "1 to a few days"),
    duurCat: "dagen",
    binnenMaand: "ja",
    vorm: ["klassikaal"],
    prijs: bi("Zie site", "See site"),
    prijsCat: "aanvraag",
    erkenning: "Branchecertificaten",
    url: "https://www.bmeopleidingen.nl/",
  },
  {
    richting: "techniek",
    veld: "infra",
    aanbieder: "Bouwmensen",
    naam: "Leerloopbaanpad zij-instromers 23+ bouw en infra",
    duur: bi("Modulair, 1 jaar, in dienst (cao Bouw)", "Modular, 1 year, employed (construction CLA)"),
    duurCat: "maanden",
    binnenMaand: "deels",
    vorm: ["werkplek"],
    prijs: bi("Betaald werk", "Paid work"),
    prijsCat: "gratis",
    erkenning: "Mbo-certificaten richting diploma",
    url: "https://bouwmensen.nl/mogelijkheden/infosheet-zij-instromers/",
  },
  {
    richting: "techniek",
    veld: "infra",
    aanbieder: "SOMA College",
    naam: "Vakman GWW / Machinist grondverzet (BBL)",
    duur: bi("2 jaar BBL", "2-year BBL"),
    duurCat: "maanden",
    binnenMaand: "nee",
    vorm: ["werkplek"],
    prijs: bi("Cao-loon", "CLA wage"),
    prijsCat: "gratis",
    erkenning: "Mbo-diploma",
    url: "https://www.soma-college.nl/infra-opleidingen/vakman-gww/",
  },
  // ===== TECHNIEK: onderhoud / gebouwbeheer =====
  {
    richting: "techniek",
    veld: "onderhoud",
    aanbieder: "ROVC",
    naam: "Cursus Onderhoudstechniek",
    duur: bi("Korte cursus", "Short course"),
    duurCat: "dagen",
    binnenMaand: "ja",
    vorm: ["klassikaal"],
    prijs: bi("Op aanvraag", "On request"),
    prijsCat: "aanvraag",
    erkenning: "ROVC-certificaat",
    url: "https://www.rovc.nl/cursus/onderhoudstechniek",
  },
  {
    richting: "techniek",
    veld: "onderhoud",
    aanbieder: "ROVC",
    naam: "Elektrische huis- en utiliteitinstallaties",
    duur: bi("7 dagen (3 praktijk), gespreid over weken", "7 days (3 practical), spread over weeks"),
    duurCat: "weken",
    binnenMaand: "deels",
    vorm: ["klassikaal"],
    prijs: bi("Op aanvraag", "On request"),
    prijsCat: "aanvraag",
    erkenning: "ROVC-certificaat",
    url: "https://www.rovc.nl/cursus/elektrische-huis-en-utiliteitinstallaties",
  },
  {
    richting: "techniek",
    veld: "onderhoud",
    aanbieder: "ROVC",
    naam: "Vakopleiding Eerste monteur gebouwbeheersystemen",
    duur: bi("Modulair", "Modular"),
    duurCat: "maanden",
    binnenMaand: "nee",
    vorm: ["klassikaal"],
    prijs: bi("Op maat", "Tailored"),
    prijsCat: "aanvraag",
    erkenning: "Branche-erkend",
    url: "https://www.rovc.nl/opleiding/eerste-monteur-gebouwbeheersystemen",
  },
  {
    richting: "techniek",
    veld: "onderhoud",
    aanbieder: "Noorderpoort / Drenthe College e.a.",
    naam: "Procesoperator A/B (BBL)",
    duur: bi("1 tot 2 jaar, baan vanaf dag 1", "1 to 2 years, a job from day 1"),
    duurCat: "maanden",
    binnenMaand: "nee",
    vorm: ["werkplek"],
    prijs: bi("Cao-loon", "CLA wage"),
    prijsCat: "gratis",
    erkenning: "Mbo-diploma niveau 2/3",
    url: "https://noorderpoort.nl/voor-studenten/opleidingen/procesoperator-a-bbl",
  },
];
