import type { Bi } from "./data";

const bi = (nl: string, en: string): Bi => ({ nl, en });

export interface Post {
  slug: string;
  date: Bi;
  title: Bi;
  teaser: Bi;
  body: Bi;
}

// Blogs. Eerste stuk oktober 2026, aanzet van Douwe; uitbreiden per stuk.
export const posts: Post[] = [
  {
    slug: "omscholing-belangrijker-dan-ooit",
    date: bi("Oktober 2026", "October 2026"),
    title: bi("Omscholing is belangrijker dan ooit", "Re-training matters more than ever"),
    teaser: bi(
      "In een exponentiële verandercurve zijn snelheid en flexibiliteit belangrijk. Langdradige reflectietrajecten moeten worden ingekort.",
      "On an exponential curve of change, speed and flexibility matter. Long-winded reflection tracks have to be shortened."
    ),
    body: bi(
      "Elke functie wordt de komende jaren door AI en robotica geraakt. Niet in één keer, wel gestaag. De grafiek op onze homepage laat het gat zien tussen wat AI theoretisch al kan en wat er vandaag in de praktijk gebeurt. Dat gat sluit, en het sluit het snelst in kantoorwerk. Zet je er de cijfers over robotica naast, dan schuift ook een groot deel van het fysieke werk mee.\n\nTegelijk blijft de vraag naar mensen in de techniek, de energie, de zorg en het onderwijs langer bestaan. Netten en installaties moeten gebouwd en onderhouden worden. De zorg en het onderwijs hebben handen en aandacht nodig die automatisering niet levert. Werk verschuift dus, en de vraag verschuift mee.\n\nDe meeste trajecten die mensen van werk naar werk moeten helpen, zijn daar niet op gebouwd. Een outplacementtraject van zes tot twaalf maanden was ontworpen voor een arbeidsmarkt die stilstond terwijl iemand nadacht. In een exponentiële verandercurve zijn snelheid en flexibiliteit belangrijker dan een lange reflectie. Langdradige trajecten moeten worden ingekort, niet omdat zorgvuldigheid er niet toe doet, maar omdat het tempo van de verandering anders wint.\n\nEconomisch succes hangt in belangrijke mate af van één vraag: hoe zorgen we voor een herverdeling van talent over sectoren? Dat vraagt drie dingen tegelijk. Werk moet loskomen van diploma's: tekortsectoren moeten openstaan voor zij-instromers, met korte, erkende leertrajecten en leren op de werkvloer. Er zit waarde in een frisse blik, en juist de nieuwe technologie maakt het makkelijker om sneller zelfstandig en productief te worden. En de mensen zelf hebben een flexibele mindset nodig: nieuwe vaardigheden aanleren en bestaande competenties op een ander terrein inzetten.\n\nReorganiseren is daarbij geen falen, wegkijken wel. Reorganiseren is soms noodzakelijk, maar komt met verantwoordelijkheid. Werkgevers hebben de ruimte nodig om meer te doen met minder mensen. In een arbeidsmarkt die steeds onzekerder wordt, groeit tegelijk de morele verplichting om goed te zorgen voor de werknemers die zich altijd hard voor de zaak hebben ingezet. Dat is precies waar HR-leiders de komende jaren het verschil maken: in het begeleiden van de organisatie naar een toekomstbestendige vorm, en in het begeleiden van de mensen van wie de functie verdwijnt.\n\nZo ziet een omscholingstraject er voor ons uit: een productieve online start zonder wachten op een afspraak, een ondersteunende intake, begeleiding door een erkende loopbaancoach die actiegericht werkt, een korte en erkende omscholing met vanaf dag één een cursus om AI in het nieuwe vak toe te passen, en een directe lijn naar werkgevers in sectoren met blijvende vraag. Zorgvuldig, maar efficiënt. Daarom draait alles bij ons om één ding: leren om te blijven leren.",
      "In the coming years every job will be touched by AI and robotics. Not all at once, but steadily. The chart on our homepage shows the gap between what AI can already do in theory and what happens in practice today. That gap is closing, fastest in office work. Add the robotics figures and a large share of physical work shifts as well.\n\nAt the same time, the demand for people in the trades, energy, care and education lasts longer. Grids and installations have to be built and maintained. Care and education need hands and attention that automation does not provide. Work is shifting, and demand shifts with it.\n\nMost of the tracks meant to move people from job to job were not built for this. An outplacement track of six to twelve months was designed for a labour market that stood still while someone thought things over. On an exponential curve of change, speed and flexibility matter more than long reflection. Long-winded tracks have to be shortened, not because care does not matter, but because the pace of change wins otherwise.\n\nEconomic success largely depends on one question: how do we redistribute talent across sectors? That takes three things at once. Work has to come loose from diplomas: shortage sectors have to open up to career switchers, with short, accredited learning tracks and learning on the job. There is value in a fresh perspective, and the new technology itself makes it easier to become independent and productive faster. And people themselves need a flexible mindset: learning new skills and applying existing competences in a different field.\n\nRestructuring is not failure here. Looking away is. Restructuring is sometimes necessary, but it comes with responsibility. Employers need room to do more with fewer people. In a labour market that grows ever more uncertain, the moral obligation grows with it: to take good care of the employees who always gave their best. That is exactly where HR leaders make the difference in the coming years: guiding the organisation into a future-proof shape, and guiding the people whose roles disappear.\n\nThis is what a re-training track looks like to us: a productive online start without waiting for an appointment, a supportive intake, guidance by an accredited career coach who works toward action, short and recognised re-training with a course on applying AI in the new trade from day one, and a direct line to employers in sectors with lasting demand. Careful, but efficient. That is why everything we do comes down to one thing: learning to keep learning."
    ),
  },
];
